version: '3'

services:
  redis-service:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    restart: always

  app:
    build: ./app
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 8080:80
